-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 23:16:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CeuOpenMed
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CeuOpenMed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CeuOpenMed` DEFAULT CHARACTER SET utf8 ;
USE `CeuOpenMed` ;

-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Adm_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Adm_Persona` (
  `IdPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PrimerNombre` NVARCHAR(45) NOT NULL,
  `SegundoNombre` NVARCHAR(45) NULL,
  `ApellidoPaterno` NVARCHAR(45) NOT NULL,
  `ApellidoMaterno` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`access_tokens` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` NVARCHAR(300) NOT NULL,
  `expires_at` INT UNSIGNED NOT NULL,
  `auth_code` NVARCHAR(200) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `app_id` NVARCHAR(200) NULL DEFAULT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  `updated_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`authorization_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`authorization_codes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` NVARCHAR(150) NOT NULL,
  `expires_at` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `app_id` NVARCHAR(200) NULL DEFAULT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  `updated_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Seg_Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Seg_Rol` (
  `IdRol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Rol` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Seg_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Seg_Usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` NVARCHAR(255) NOT NULL,
  `auth_key` NVARCHAR(32) NOT NULL,
  `password_hash` NVARCHAR(255) NOT NULL,
  `password_reset_token` NVARCHAR(255) NULL DEFAULT NULL,
  `email` NVARCHAR(255) NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT UNSIGNED NOT NULL,
  `updated_at` INT UNSIGNED NOT NULL,
  `IdRol` INT UNSIGNED NOT NULL,
  `IdPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC),
  INDEX `FK_Seg_Usuario_REF_Seg_Rol_idx` (`IdRol` ASC),
  INDEX `FK_Seg_Usuario_REF_Adm_Persona1_idx` (`IdPersona` ASC),
  CONSTRAINT `FK_Seg_Usuario_REF_Seg_Rol`
    FOREIGN KEY (`IdRol`)
    REFERENCES `CeuOpenMed`.`Seg_Rol` (`IdRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Seg_Usuario_REF_Adm_Persona1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `CeuOpenMed`.`Adm_Persona` (`IdPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Profesor` (
  `IdProfesor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdProfesor`),
  INDEX `FK_Doc_Profesor_REF_Adm_Persona1_idx` (`IdPersona` ASC),
  CONSTRAINT `FK_Doc_Profesor_REF_Adm_Persona1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `CeuOpenMed`.`Adm_Persona` (`IdPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Especialidad` (
  `IdEspecialidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Especialidad` NVARCHAR(150) NOT NULL,
  PRIMARY KEY (`IdEspecialidad`),
  UNIQUE INDEX `Especialidad_UNIQUE` (`Especialidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Grupo` (
  `IdGrupo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Grupo` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdGrupo`),
  UNIQUE INDEX `Grupo_UNIQUE` (`Grupo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Estudiante` (
  `IdEstudiante` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdPersona` INT UNSIGNED NOT NULL,
  `IdGrupo` INT UNSIGNED NULL,
  PRIMARY KEY (`IdEstudiante`),
  INDEX `FK_Doc_Estudiante_REF_Adm_Persona1_idx` (`IdPersona` ASC),
  INDEX `FK_Doc_Estudiante_REF_Doc_Grupo1_idx` (`IdGrupo` ASC),
  CONSTRAINT `FK_Doc_Estudiante_REF_Adm_Persona1`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `CeuOpenMed`.`Adm_Persona` (`IdPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doc_Estudiante_REF_Doc_Grupo1`
    FOREIGN KEY (`IdGrupo`)
    REFERENCES `CeuOpenMed`.`Doc_Grupo` (`IdGrupo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Profesor_has_Doc_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Profesor_has_Doc_Grupo` (
  `IdProfesor` INT UNSIGNED NOT NULL,
  `IdGrupo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdProfesor`, `IdGrupo`),
  INDEX `FK_Doc_Profesor_has_Doc_Grupo_REF_Doc_Grupo1_idx` (`IdGrupo` ASC),
  INDEX `FK_Doc_Profesor_has_Doc_Grupo_REF_Doc_Profesor1_idx` (`IdProfesor` ASC),
  CONSTRAINT `FK_Doc_Profesor_has_Doc_Grupo_REF_Doc_Profesor1`
    FOREIGN KEY (`IdProfesor`)
    REFERENCES `CeuOpenMed`.`Doc_Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doc_Profesor_has_Doc_Grupo_REF_Doc_Grupo1`
    FOREIGN KEY (`IdGrupo`)
    REFERENCES `CeuOpenMed`.`Doc_Grupo` (`IdGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Tipo_Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Tipo_Entidad` (
  `IdTipoEntidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TipoEntidad` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdTipoEntidad`),
  UNIQUE INDEX `TipoEntidad_UNIQUE` (`TipoEntidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Idioma` (
  `IdIdioma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Idioma` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdIdioma`),
  UNIQUE INDEX `Idioma_UNIQUE` (`Idioma` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Entidad` (
  `IdEntidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdTipoEntidad` INT UNSIGNED NOT NULL,
  `IdEstudiante` INT UNSIGNED NOT NULL,
  `IdProfesor` INT UNSIGNED NULL,
  `Evaluacion` INT NULL,
  `Estado` TINYINT NOT NULL,
  `Comentario` TEXT NULL,
  PRIMARY KEY (`IdEntidad`),
  INDEX `FK_Entidad_REF_Tipo_Entidad1_idx` (`IdTipoEntidad` ASC),
  INDEX `FK_Entidad_REF_Doc_Estudiante1_idx` (`IdEstudiante` ASC),
  INDEX `FK_Entidad_REF_Doc_Profesor1_idx` (`IdProfesor` ASC),
  CONSTRAINT `FK_Entidad_REF_Tipo_Entidad1`
    FOREIGN KEY (`IdTipoEntidad`)
    REFERENCES `CeuOpenMed`.`Tipo_Entidad` (`IdTipoEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Entidad_REF_Doc_Estudiante1`
    FOREIGN KEY (`IdEstudiante`)
    REFERENCES `CeuOpenMed`.`Doc_Estudiante` (`IdEstudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Entidad_REF_Doc_Profesor1`
    FOREIGN KEY (`IdProfesor`)
    REFERENCES `CeuOpenMed`.`Doc_Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Tipo_Asociacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Tipo_Asociacion` (
  `IdTipoAsociacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdTipoEntidad1` INT UNSIGNED NOT NULL,
  `IdTipoEntidad2` INT UNSIGNED NOT NULL,
  `TipoAsociacion` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoAsociacion`),
  INDEX `FK_Tipo_Asociacion_REF_Tipo_Entidad1_idx` (`IdTipoEntidad1` ASC),
  INDEX `FK_Tipo_Asociacion_REF_Tipo_Entidad2_idx` (`IdTipoEntidad2` ASC),
  CONSTRAINT `FK_Tipo_Asociacion_REF_Tipo_Entidad1`
    FOREIGN KEY (`IdTipoEntidad1`)
    REFERENCES `CeuOpenMed`.`Tipo_Entidad` (`IdTipoEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Tipo_Asociacion_REF_Tipo_Entidad2`
    FOREIGN KEY (`IdTipoEntidad2`)
    REFERENCES `CeuOpenMed`.`Tipo_Entidad` (`IdTipoEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Asociacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Asociacion` (
  `IdAsociacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdEntidad1` INT UNSIGNED NOT NULL,
  `IdEntidad2` INT UNSIGNED NOT NULL,
  `IdTipoAsociacion` INT UNSIGNED NOT NULL,
  `IdEstudiante` INT UNSIGNED NOT NULL,
  `IdProfesor` INT UNSIGNED NULL,
  `Evaluacion` INT NULL,
  `Estado` TINYINT NOT NULL,
  `Nivel` INT NULL,
  `Comentario` TEXT NULL,
  PRIMARY KEY (`IdAsociacion`),
  INDEX `FK_Asociacion_REF_Entidad1_idx` (`IdEntidad1` ASC),
  INDEX `FK_Asociacion_REF_Entidad2_idx` (`IdEntidad2` ASC),
  INDEX `FK_Asociacion_REF_Tipo_Asociacion1_idx` (`IdTipoAsociacion` ASC),
  INDEX `FK_Asociacion_REF_Doc_Estudiante1_idx` (`IdEstudiante` ASC),
  INDEX `FK_Asociacion_REF_Doc_Profesor1_idx` (`IdProfesor` ASC),
  CONSTRAINT `FK_Asociacion_REF_Entidad1`
    FOREIGN KEY (`IdEntidad1`)
    REFERENCES `CeuOpenMed`.`Entidad` (`IdEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_REF_Entidad2`
    FOREIGN KEY (`IdEntidad2`)
    REFERENCES `CeuOpenMed`.`Entidad` (`IdEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_REF_Tipo_Asociacion1`
    FOREIGN KEY (`IdTipoAsociacion`)
    REFERENCES `CeuOpenMed`.`Tipo_Asociacion` (`IdTipoAsociacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_REF_Doc_Estudiante1`
    FOREIGN KEY (`IdEstudiante`)
    REFERENCES `CeuOpenMed`.`Doc_Estudiante` (`IdEstudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_REF_Doc_Profesor1`
    FOREIGN KEY (`IdProfesor`)
    REFERENCES `CeuOpenMed`.`Doc_Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Doc_Profesor_has_Doc_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Doc_Profesor_has_Doc_Especialidad` (
  `IdProfesor` INT UNSIGNED NOT NULL,
  `IdEspecialidad` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdProfesor`, `IdEspecialidad`),
  INDEX `FK_Doc_Profesor_has_Doc_Especialidad_REF_Doc_Especialidad1_idx` (`IdEspecialidad` ASC),
  INDEX `FK_Doc_Profesor_has_Doc_Especialidad_REF_Doc_Profesor1_idx` (`IdProfesor` ASC),
  CONSTRAINT `FK_Doc_Profesor_has_Doc_Especialidad_REF_Doc_Profesor1`
    FOREIGN KEY (`IdProfesor`)
    REFERENCES `CeuOpenMed`.`Doc_Profesor` (`IdProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Doc_Profesor_has_Doc_Especialidad_REF_Doc_Especialidad1`
    FOREIGN KEY (`IdEspecialidad`)
    REFERENCES `CeuOpenMed`.`Doc_Especialidad` (`IdEspecialidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Detalle_Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Detalle_Entidad` (
  `IdRecurso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdIdioma` INT UNSIGNED NOT NULL,
  `IdEntidad` INT UNSIGNED NOT NULL,
  `Entidad` TEXT NOT NULL,
  `Nivel` INT NULL,
  PRIMARY KEY (`IdRecurso`),
  INDEX `FK_Detalle_Entidad_REF_Idioma1_idx` (`IdIdioma` ASC),
  INDEX `FK_Detalle_Entidad_REF_Entidad1_idx` (`IdEntidad` ASC),
  CONSTRAINT `FK_Detalle_Entidad_REF_Idioma1`
    FOREIGN KEY (`IdIdioma`)
    REFERENCES `CeuOpenMed`.`Idioma` (`IdIdioma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Detalle_Entidad_REF_Entidad1`
    FOREIGN KEY (`IdEntidad`)
    REFERENCES `CeuOpenMed`.`Entidad` (`IdEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Recurso` (
  `IdRecurso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdEntidad` INT UNSIGNED NOT NULL,
  `Nivel` INT NOT NULL,
  `URL` NVARCHAR(255) NOT NULL,
  `IsImage` BIT NOT NULL,
  PRIMARY KEY (`IdRecurso`),
  INDEX `FK_Recurso_REF_Entidad1_idx` (`IdEntidad` ASC),
  CONSTRAINT `FK_Recurso_REF_Entidad1`
    FOREIGN KEY (`IdEntidad`)
    REFERENCES `CeuOpenMed`.`Entidad` (`IdEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Recurso_Descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Recurso_Descripcion` (
  `IdRecursoDescripcion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdRecurso` INT UNSIGNED NOT NULL,
  `IdIdioma` INT UNSIGNED NOT NULL,
  `Descripcion` TEXT NOT NULL,
  PRIMARY KEY (`IdRecursoDescripcion`),
  INDEX `FK_Recurso_Descripcion_REF_Idioma1_idx` (`IdIdioma` ASC),
  INDEX `FK_Recurso_Descripcion_REF_Recurso1_idx` (`IdRecurso` ASC),
  CONSTRAINT `FK_Recurso_Descripcion_REF_Idioma1`
    FOREIGN KEY (`IdIdioma`)
    REFERENCES `CeuOpenMed`.`Idioma` (`IdIdioma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Recurso_Descripcion_REF_Recurso1`
    FOREIGN KEY (`IdRecurso`)
    REFERENCES `CeuOpenMed`.`Recurso` (`IdRecurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Tipo_Asociacion_Multiple`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Tipo_Asociacion_Multiple` (
  `IdTipoAsociacionMultiple` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdTipoEntidad` INT UNSIGNED NOT NULL,
  `TipoAsociacion` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTipoAsociacionMultiple`),
  INDEX `FK_Tipo_Asociacion_Multiple_REF_Tipo_Entidad1_idx` (`IdTipoEntidad` ASC),
  CONSTRAINT `FK_Tipo_Asociacion_Multiple_REF_Tipo_Entidad1`
    FOREIGN KEY (`IdTipoEntidad`)
    REFERENCES `CeuOpenMed`.`Tipo_Entidad` (`IdTipoEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CeuOpenMed`.`Asociacion_Multiple`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CeuOpenMed`.`Asociacion_Multiple` (
  `IdAsociacionMultiple` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdAsociacion` INT UNSIGNED NOT NULL,
  `IdEntidad` INT UNSIGNED NULL,
  `IdTipoEntidad` INT UNSIGNED NULL,
  `IdTipoAsociacionMultiple` INT UNSIGNED NULL,
  PRIMARY KEY (`IdAsociacionMultiple`),
  INDEX `FK_Asociacion_Multiple_REF_Asociacion1_idx` (`IdAsociacion` ASC),
  INDEX `FK_Asociacion_Multiple_REF_Entidad1_idx` (`IdEntidad` ASC),
  INDEX `FK_Asociacion_Multiple_REF_Tipo_Asociacion_Multiple1_idx` (`IdTipoAsociacionMultiple` ASC),
  CONSTRAINT `FK_Asociacion_Multiple_REF_Asociacion1`
    FOREIGN KEY (`IdAsociacion`)
    REFERENCES `CeuOpenMed`.`Asociacion` (`IdAsociacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_Multiple_REF_Entidad1`
    FOREIGN KEY (`IdEntidad`)
    REFERENCES `CeuOpenMed`.`Entidad` (`IdEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Asociacion_Multiple_REF_Tipo_Asociacion_Multiple1`
    FOREIGN KEY (`IdTipoAsociacionMultiple`)
    REFERENCES `CeuOpenMed`.`Tipo_Asociacion_Multiple` (`IdTipoAsociacionMultiple`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `CeuOpenMed`;

DELIMITER $$
USE `CeuOpenMed`$$
CREATE DEFINER = CURRENT_USER TRIGGER `CeuOpenMed`.`Entidad_BEFORE_INSERT` BEFORE INSERT ON `Entidad` FOR EACH ROW
BEGIN
	SET @existprof = (SELECT COUNT(*) FROM `doc_profesor` WHERE `IdProfesor` = NEW.IdProfesor);
	IF @existprof != 1 THEN
		SET NEW.IdProfesor = NULL;
	END IF;
END$$

USE `CeuOpenMed`$$
CREATE DEFINER = CURRENT_USER TRIGGER `CeuOpenMed`.`Asociacion_BEFORE_INSERT` BEFORE INSERT ON `Asociacion` FOR EACH ROW
BEGIN
SET @existprof = (SELECT COUNT(*) FROM `doc_profesor` WHERE `IdProfesor` = NEW.IdProfesor);
	IF @existprof != 1 THEN
		SET NEW.IdProfesor = NULL;
	END IF;
END$$

USE `CeuOpenMed`$$
CREATE DEFINER = CURRENT_USER TRIGGER `CeuOpenMed`.`Asociacion_Multiple_BEFORE_INSERT` BEFORE INSERT ON `Asociacion_Multiple` FOR EACH ROW
BEGIN
	SET @existEnt = (SELECT COUNT(*) FROM `entidad` WHERE `IdEntidad` = NEW.IdEntidad);
	IF @existEnt != 1 THEN
		SET NEW.IdEntidad = NULL;
	END IF;
    
    SET @existTipAsoc = (SELECT COUNT(*) FROM `tipo_asociacion_multiple` WHERE `IdTipoAsociacionMultiple` = NEW.IdTipoAsociacionMultiple);
	IF @existTipAsoc != 1 THEN
		SET NEW.IdTipoAsociacionMultiple = NULL;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `CeuOpenMed`.`Adm_Persona`
-- -----------------------------------------------------
START TRANSACTION;
USE `CeuOpenMed`;
INSERT INTO `CeuOpenMed`.`Adm_Persona` (`IdPersona`, `PrimerNombre`, `SegundoNombre`, `ApellidoPaterno`, `ApellidoMaterno`) VALUES (1, 'Administrador', '', 'de', 'Red');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CeuOpenMed`.`Seg_Rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `CeuOpenMed`;
INSERT INTO `CeuOpenMed`.`Seg_Rol` (`IdRol`, `Rol`) VALUES (1, 'Administrador');
INSERT INTO `CeuOpenMed`.`Seg_Rol` (`IdRol`, `Rol`) VALUES (2, 'Profesor');
INSERT INTO `CeuOpenMed`.`Seg_Rol` (`IdRol`, `Rol`) VALUES (3, 'Estudiante');

COMMIT;


-- -----------------------------------------------------
-- Data for table `CeuOpenMed`.`Seg_Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `CeuOpenMed`;
INSERT INTO `CeuOpenMed`.`Seg_Usuario` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `status`, `created_at`, `updated_at`, `IdRol`, `IdPersona`) VALUES (1, 'administrator', 'vSC8oRwXoFe1bzo-2X0zCL_2c6M3o6sF', '$2y$13$1qDEFAS8g1VVvNjfyLq5u.7qsYY/1fLFKfYXesCxtot8npIJR7SLS', NULL, 'admin@mybussines.com', 10, 1563490124, 1563490124, 1, 1);

COMMIT;

